language: go
cache:
  directories:
  - $GOCACHE
  - $GOPATH/src/github.com/grpc-ecosystem
  - $GOPATH/src/gopkg.in/alecthomas
  - $GOPATH/src/google.golang.org

go:
  - "1.13.x"

env:
  global:
    - GOCACHE=$HOME/.go-build

sudo: required

before_script:
  - bash ./scripts/install_travis_proto.sh

script:
  - export GO111MODULE=on
  - make rpc-check
  - make lint unit

after_script:
  - echo "Uploading to termbin.com..." && find *.log | xargs -I{} sh -c "cat {} | nc termbin.com 9999 | xargs -r0 printf '{} uploaded to %s'"
  - echo "Uploading to file.io..." && tar -zcvO *.log | curl -s -F 'file=@-;filename=logs.tar.gz' https://file.io | xargs -r0 printf 'logs.tar.gz uploaded to %s\n'
